# Generated by Django 5.0.7 on 2024-07-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('lote', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
                'db_table': 'cartao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero'], name='cartao_numero_3379a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoteCartoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('data', models.CharField(blank=True, max_length=8)),
                ('numero', models.CharField(blank=True, max_length=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Cartões',
                'verbose_name_plural': 'Lotes de Cartões',
                'db_table': 'lote_cartoes',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
