# Generated by Django 5.0.7 on 2024-07-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_cartao_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='numero',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='lotecartoes',
            name='numero',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
